# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MvvmDemoFireBase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Moya'
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseDatabase'
  pod 'Firebase'
  pod 'SDWebImage', '~> 5.0'
  pod 'RxSwift'
  pod 'RxCocoa'

  # Pods for MvvmDemoFireBase

end
